#!/bin/bash
# Installs Ontotagger in this directory, Framenet-SRL and Nominal-Events in parallel-directories.
# Installs https://github.com/cltl/vua-resources.git if it isn't there already.
thisdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $thisdir
cd ..
socketdir=`pwd`
cd ${thisdir}


# Github cloning may fail occasionally. Therefore, retry if it fails.
function clone_githup_repo () {
    local reponame=$1
    local repourl=$2
    local commitset=$3
    local maxtrials=10
    local res=0
    local trial=0
    local go_on=0
    while
	[ $go_on == 0 ]
    do
 	git clone $repourl
	res=$?
	if
	    [ $res == 0 ]
	then
	    cd $reponame
	    git checkout $commitset
	    go_on=1
	else
	    trial=$((trial+1))
	    if
		[ $trial -gt $maxtrials ]
	    then
		go_on=1
	    fi
	fi
    done
}


function  check_install_vua_resources () {
    if
	[ ! -d "${socketdir}/vua-resources" ]
    then
	echo "NOTE: Please check whether vua-resources has been installed in ${socketdir}" >&2 
    fi
}

# function check_install_vua_resources () {
#   local reponame=vua-resources
#    local repourl="https://github.com/cltl/vua-resources.git"
#    local commitset=e730ce672f2a13457393028b679e9147334c490e
#    if
#	[ ! -d "${socketdir}/vua-resources" ]
#    then
#	cd ${socketdir}
#	clone_githup_repo $reponame $repourl $commitset
#	git clone https://github.com/cltl/vua-resources.git
#    fi  
#}


function install_derived_module () {
  local derived_module=$1
  local runfile_template=$2
  local runfile="${derived_module}/run"
  cd ${thisdir}
  if
      [ ! -d "../${derived_module}" ]
  then
      mkdir -p "../${derived_module}"
      if 
	  [ $? -gt 0 ]
      then
	  echo "Cannot create ${derived_module}"
	  exit 1
      fi
      cp ${runfile_template} ../${derived_module}/run
      chmod 775 ../${derived_module}/run
  fi
}

cd ${thisdir}
check_install_vua_resources
install_derived_module Framenet_SRL Framenet_SRL_runscript
install_derived_module Nominal_Events Nominal_Events_runscript

set -e
mvn install
cd target
jarfile=`ls -1 ontotagger-*-jar-with-dependencies.jar`
cd ${thisdir}
mkdir -p ${thisdir}/lib
mv "$thisdir/target/$jarfile" "$thisdir/lib"

#cd "$thisdir"
#rm -R target
#rm -R src
